source ~/.vim/includes/plug.vimrc
source ~/.vim/includes/std.vimrc

source ~/.vim/includes/gui.vimrc
source ~/.vim/includes/has_colors.vimrc
source ~/.vim/includes/fugitive.vimrc
source ~/.vim/includes/minibuf.vimrc
source ~/.vim/includes/nerdtree.vimrc
source ~/.vim/includes/mappings.vimrc
source ~/.vim/includes/stevelosh.vimrc
source ~/.vim/includes/go.vimrc
source ~/.vim/includes/json.vimrc
